package kiwiapollo.cobblemontrainerbattle.common;

public enum CommandConditionType {
    EMPTY_PLAYER_PARTY,
    FAINTED_PLAYER_PARTY,
    BELOW_RELATIVE_LEVEL_THRESHOLD,
    BUSY_WITH_POKEMON_BATTLE,
    VALID_SESSION_EXISTS,
    VALID_SESSION_NOT_EXISTS,
    DEFEATED_ALL_TRAINERS,
    DEFEATED_ANY_TRAINERS,
    DEFEATED_NO_TRAINER,
    DEFEATED_TO_TRAINER,
    POKEMON_TRADED
}
